version: '3'
services:
  web:
    build: .
    image: flask_service
    ports:
      - "8123:8123"
  db:
    image: postgres:15.1
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"